pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=ci/circleci
      - status-success=GolangCI
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: rebase
