version: 2

jobs:
  # Test Jobs
  build:
    docker:
      - image: golang:1.12.7
    steps:
      - checkout
      - run: make build

  test:
    docker:
      - image: golang:1.12.7
    steps:
      - checkout
      - run: make test/ci

  e2e-tests:
    docker:
      - image: golang:1.12.7
    steps:
      - checkout
      - run: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: |
          mkdir .well-known
          make e2e
          make e2e/env-stop

  e2e-tests/nocache:
    docker:
      - image: golang:1.12.7
    steps:
      - checkout
      - run: |
          curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: |
          mkdir .well-known
          REDIS_HOST=nocache make e2e
          make e2e/env-stop

  # Deploy Jobs
  deploy/sandbox:
    docker:
      - image: golang:1.12.7
    steps:
      - run: |
          curl -X POST \
               -F token=$GITLAB_CI_TOKEN \
               -F ref=master \
               -F "variables[GIT_SHA1]=$CIRCLE_SHA1" \
               -F "variables[CI_COMMIT_SHA]=$CIRCLE_SHA1" \
               https://gitlab.skypicker.com/api/v4/projects/1680/trigger/pipeline

  publish/docs:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/www
    environment:
      HUGO_BUILD_DIR: ~/www/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run:
          name: Set author of the commit
          command: |
            git config user.email "ci-build@kiwi.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "9c:b5:0a:f1:d1:6f:49:34:d3:81:10:81:cd:cc:6c:d5"
      - run: make docs/publish

workflows:
  version: 2
  build:
    jobs:
      - build
  test:
    jobs:
      - test
      - e2e-tests
      - e2e-tests/nocache
  deploy:
    jobs:
      - deploy/sandbox: &only-master
          filters:
            branches:
              only:
                - master
      - publish/docs: *only-master
