name: Commitsar
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Commitsar Action
        uses: commitsar-app/commitsar@v0.6.4
