name: Go
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.12, 1.13]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -d ./...
      - name: Test
        run: make test/ci
