name: Linters
on:
  pull_request:
    branches:
      - master

jobs:
  protool:
    name: Protool
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Protool lint
        uses: docker://uber/prototool
  swagger:
    name: Swagger
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Swagger Lint
        uses: docker://quay.io/goswagger/swagger
        with:
          args: validate ./api/swagger.yml
  golang-ci-lint:
    name: Lint the project using GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Run GolangCI-Lint
        uses: matoous/golangci-lint-action@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .golangci.yml
  revive-lint:
    name: Lint the project using Revive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Run Revive
        uses: docker://morphy/revive-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config: .revive.toml
