name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release-notary:
    name: Release Notes
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Publish Release Notes
        uses: commitsar-app/release-notary@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
